# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Visual Studio Enterprise Subscription (69f26762-afa0-46b5-8311-4fbdf35b3060)'
    subscriptionId: '69f26762-afa0-46b5-8311-4fbdf35b3060'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'Gethu-AKS-RG'
    location: 'East US'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/gethuravi2020/ghost-app/main/infra/AKS/azuredeploy.json'
    csmParametersFileLink: 'https://raw.githubusercontent.com/gethuravi2020/ghost-app/main/infra/AKS/azuredeploy.parameters.json'
    deploymentMode: 'Incremental'
    deploymentOutputs: aks_arm
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Visual Studio Enterprise Subscription (69f26762-afa0-46b5-8311-4fbdf35b3060)'
    subscriptionId: '69f26762-afa0-46b5-8311-4fbdf35b3060'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'Gethu-AKS-RG'
    location: 'East US'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/gethuravi2020/ghost-app/main/infra/ACR/azuredeploy.json'
    csmParametersFileLink: 'https://raw.githubusercontent.com/gethuravi2020/ghost-app/main/infra/ACR/azuredeploy.parameters.json'
    deploymentMode: 'Incremental'
    deploymentOutputs: acr_arm
- powershell: |
    Write-Host "Output of the AKS Deployment is : $(aks_arm)"
    Write-Host "Output of the AKS Deployment is : $(acr_arm)"
    ${env:AZURE_DEVOPS_EXT_PAT} = "jiliqrniv5wfknnouby3i5fwforivczlnnxjvffajlr2gkxhl7pa"
    az pipelines variable-group variable create --group-id 4 --name "$(aks_arm.akS-NAME.value)" --value $value --org https://dev.azure.com/ravij2020/ --project ITOps

#- pwsh: $(System.DefaultWorkingDirectory)/parse_arm_deployment_output.ps1 -ArmOutputString '${env:aks_arm}' -MakeOutput -ErrorAction Stop
#- task: AzurePowerShell@5
#  inputs:
#    azureSubscription: 'Visual Studio Enterprise Subscription (69f26762-afa0-46b5-8311-4fbdf35b3060)'
#    ScriptType: 'InlineScript'
#    Inline: 'az pipelines variable-group variable create'
#    ScriptArguments: '--group-id 1 --name ${env:keyname}" --value ${env:value} --org https://dev.azure.com/ravij2020/ --project ITOps'
#    errorActionPreference: 'continue'
#    azurePowerShellVersion: 'LatestVersion'
#    $(System.DefaultWorkingDirectory)/parse_arm_deployment_output.ps1 -ArmOutputString $(aks_arm) -MakeOutput -ErrorAction Stop
