# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Visual Studio Enterprise Subscription (69f26762-afa0-46b5-8311-4fbdf35b3060)'
    subscriptionId: '69f26762-afa0-46b5-8311-4fbdf35b3060'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'Gethu-AKS-RG'
    location: 'East US'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/gethuravi2020/ghost-app/main/infra/AKS/azuredeploy.json'
    csmParametersFileLink: 'https://raw.githubusercontent.com/gethuravi2020/ghost-app/main/infra/AKS/azuredeploy.parameters.json'
    deploymentMode: 'Incremental'
    deploymentOutputs: aks_arm
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Visual Studio Enterprise Subscription (69f26762-afa0-46b5-8311-4fbdf35b3060)'
    subscriptionId: '69f26762-afa0-46b5-8311-4fbdf35b3060'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'Gethu-AKS-RG'
    location: 'East US'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/gethuravi2020/ghost-app/main/infra/ACR/azuredeploy.json'
    csmParametersFileLink: 'https://raw.githubusercontent.com/gethuravi2020/ghost-app/main/infra/ACR/azuredeploy.parameters.json'
    deploymentMode: 'Incremental'
    deploymentOutputs: acr_arm
- powershell: |
    Write-Host "Output of the AKS Deployment is : $(aks_arm)"
    Write-Host "Output of the AKS Deployment is : $(acr_arm)"
- task: AzureCLI@2
  inputs:
    azureSubscription: 'Azure subscription 1 (ad44404d-2ae3-4c48-8c53-40751b702244)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'az pipelines variable-group variable create --group-id 1 --name aks-name --value $(aks_arm) --output table'
- task: AzureCLI@2
  inputs:
    azureSubscription: 'Azure subscription 1 (ad44404d-2ae3-4c48-8c53-40751b702244)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'az pipelines variable-group variable create --group-id 1 --name acr-name --value $(acr_arm) --output table'


