# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Azure Container Registry'
    azureSubscription: 'Visual Studio Enterprise Subscription (69f26762-afa0-46b5-8311-4fbdf35b3060)'
    azureContainerRegistry: '{"loginServer":"gethuraviacrdemo.azurecr.io", "id" : "/subscriptions/69f26762-afa0-46b5-8311-4fbdf35b3060/resourceGroups/myResourceGroup/providers/Microsoft.ContainerRegistry/registries/gethuraviacrdemo"}'
    dockerComposeFile: '**/docker-compose.yml'
    action: 'Build services'
- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Azure Container Registry'
    azureSubscription: 'Visual Studio Enterprise Subscription (69f26762-afa0-46b5-8311-4fbdf35b3060)'
    azureContainerRegistry: '{"loginServer":"gethuraviacrdemo.azurecr.io", "id" : "/subscriptions/69f26762-afa0-46b5-8311-4fbdf35b3060/resourceGroups/myResourceGroup/providers/Microsoft.ContainerRegistry/registries/gethuraviacrdemo"}'
    dockerComposeFile: '**/docker-compose.yml'
    action: 'Push services'